matrix:
  include:
    language: python
    python: 3.7
    dist: xenial
    sudo: true
    install: 
      - pip install GitPython 
      - pip install inotify 


    before_script:
      - sudo chmod +x ./daemon/test/test.sh
    script:
      - ./daemon/test/test.sh
